### ISSUE TITLE
Twig: Fix hero and rich text in ILO base theme

### ISSUE THREAD

**Issue by Shashika6** [international-labour-organization/ilo_base_theme#18]
The hero card text and rich text images are not rendering. 

![Image](https://github.com/international-labour-organization/ilo_base_theme/assets/32934169/c1a83cef-9419-43f1-b39e-ba4bd6936db3)

**Comment by ademarco** [comment]
@Shashika6  this is actually due to the fact that, on UI Patterns 1.x, when a preview value is an array, UI Patterns prefixes its values with `#`, to turn this into a Drupal render array. This was a bad idea and it was removed in UI Patterns 2.x. For the moment we can set `escape: false` on all patterns definitions that need it. I'm thinking of doing this on the theme side, since this is not something that concerns the design library, and it will be removed when we move to UI Patterns 2.x.

\cc @justintemps @GGKapanadze @bashlk
