### ISSUE TITLE
Accommodate the new storybook implementation

### ISSUE THREAD

**Issue by ademarco** [international-labour-organization/ilo_base_theme#26]
According to [this milestone](https://github.com/international-labour-organization/designsystem/milestone/8), the Design System is undergoing a significant refactoring. This includes renaming the pattern definition files to `*.component.yml` and adopting ES modules for JavaScript assets. The purpose of this ticket is to adapt to the new Storybook implementation.

**Comment by bashlk** [comment]
Agreed in https://github.com/international-labour-organization/designsystem/issues/1115 that we won't be proceeding with ES modules. So the only change is the naming of yml files, the removal of the individual CSS files and the directory structure, which now follows the project directory structure instead of having new folders for subcomponents.
